export const ADD_TODO = 'ADD_TODO';
export const COMPLETE_TODO = 'COMPLETE_TODO';
export const RECEIVE_TODOS = 'RECEIVE_TODOS';
export const SWAP_TODOS = 'SWAP_TODOS';
export const TOGGLE_COMPLETED_TODOS = 'TOGGLE_COMPLETED_TODOS';
export const UNCOMPLETE_TODO = 'UNCOMPLETE_TODO';
