export const ADD_TODO = 'ADD_TODO';
export const COMPLETE_TODO = 'COMPLETE_TODO';
export const RECEIVE_TODOS = 'RECEIVE_TODOS';
export const REQUEST_TODOS = 'REQUEST_TODOS';
export const REQUEST_TODO_UPDATE = 'REQUEST_TODO_UPDATE';
export const TOGGLE_COMPLETED_TODOS = 'TOGGLE_COMPLETED_TODOS';
export const UNCOMPLETE_TODO = 'UNCOMPLETE_TODO';
export const UPDATE_TODO_POSITIONS = 'UPDATE_TODO_POSITIONS';
